funFacts = [
    "Outside the USA, Ireland is the largest software producing country in the world.",
    "Bill Gates' first business was Traff-O-Data, a company that created machines which recorded the number of cars passing a given point on a road.",
    "Camels are called \"ships of the desert\" because of the way they move, not because of their transport capabilities. A Dromedary camel has one hump and a Bactrian camel two humps. The humps are used as fat storage. Thus, an undernourished camel will not have a hump. ",
    "A person can live without food for about a month, but only about a week without water. If the amount of water in your body is reduced by just 1%, you'll feel thirsty. If it's reduced by 10%, you'll die.",
    "In 1955 the richest woman in the world was Mrs Hetty Green Wilks, who left an estate of $95 million in a will that was found in a tin box with four pieces of soap. Queen Elizabeth of Britain and Queen Beatrix of the Netherlands count under the 10 wealthiest women in the world. ",
    "Over the last 150 years the average height of people in industrialised nations has increased 10 cm (about 4 inches). In the 19th century, American men were the tallest in the world, averaging 1,71m (5'6\"). Today, the average height for American men is 1,75m (5'7\"), compared to 1,77 (5'8\") for Swedes, and 1,78 (5'8.5\") for the Dutch. The tallest nation in the world is the Watusis of Burundi.",
    "Money notes are not made from paper, they are made mostly from a special blend of cotton and linen. In 1932, when a shortage of cash occurred in Tenino, Washington, USA, notes were made out of wood for a brief period.",
    "A crocodile can't move its tongue and cannot chew. Its digestive juices are so strong that it can digest a steel nail. ",
    "Like fingerprints, everyone's tongue print is different.",
    "Most lipstick contains fish scales.",
    "In the course of an average lifetime you will, while sleeping, eat 70 assorted insects and 10 spiders.",
    "A duck's quack doesn't echo, and no one knows why.",
    "Thirty-five percent of the people who use personal ads for dating are already married.",
    "The cigarette lighter was invented before the match.",
    "If you try to suppress a sneeze, you can rupture a blood vessel in your head or neck and die.",
    "If you sneeze too hard, you can fracture a rib.",
    "More than 50% of the people in the world have never made or received a telephone call.",
    "It is physically impossible for pigs to look up into the sky.",
    "In a study of 200,000 ostriches over a period of 80 years, no one reported a single case where an ostrich buried its head in the sand.",
    "Every human spent about half an hour as a single cell.",
    "Every year about 98% of atoms in your body are replaced.",
    "Hot water is heavier than cold.",
    "If you went out into space, you would explode before you suffocated because there's no air pressure.",
    "The radioactive substance, Americanium - 241 is used in many smoke detectors.",
    "Sound travels 15 times faster through steel than through the air.",
    "On average, half of all false teeth have some form of radioactivity.",
    "Only one satellite has been ever been destroyed by a meteor: the European Space Agency's Olympus in 1993.",
    "Starch is used as a binder in the production of paper. It is the use of a starch coating that controls ink penetration when printing. Cheaper papers do not use as much starch, and this is why your elbows get black when you are leaning over your morning paper.",
    "A ball of glass will bounce higher than a ball of rubber. A ball of solid steel will bounce higher than one made entirely of glass.",
    "A chip of silicon a quarter-inch square has the capacity of the original 1949 ENIAC computer, which occupied a city block.",
    "An ordinary TNT bomb involves atomic reaction, and could be called an atomic bomb. What we call an A-bomb involves nuclear reactions and should be called a nuclear bomb.",
    "At a jet plane's speed of 1,000 km (620mi) per hour, the length of the plane becomes one atom shorter than its original length.",
    "On December 23, 1947, Bell Telephone Laboratories in Murray Hill, N.J., held a secret demonstration of the transistor which marked the foundation of modern electronics.",
    "Ostriches are often not taken seriously. They can run faster than horses, and the males can roar like lions.",
    "Sloths take two weeks to digest their food.",
    "According to the Wall Street Journal, the cockfighting market is huge: The Philippines has five million roosters used for exactly that.",
    "The porpoise is second to man as the most intelligent animal on the planet.",
    "Sharks and rays are the only animals known to man that don't get cancer. Scientists believe this has something to do with the fact that they don't have bones, but cartilage.",
    "The duckbill platypus can store as many as six hundred worms in the pouches of its cheeks.",
    "Human birth control pills work on gorillas.",
    "Gorillas sleep as much as fourteen hours per day.",
    "A biological reserve has been made for golden toads because they are so rare.",
    "Jellyfish like salt water. A rainy season often reduces the jellyfish population by putting more fresh water into normally salty waters where they live.",
    "The female lion does ninety percent of the hunting.",
    "The odds of seeing three albino deer at once are one in seventy-nine billion, yet one man in Boulder Junction, Wisconsin, took a picture of three albino deer in the wood",
    "Cats often rub up against people and furniture to lay their scent and mark their territory. They do it this way, as opposed to the way dogs do it, because they have scent glands in their faces.",
    "The 57 on Heinz ketchup bottle represents the varieties of pickle the company once had. ",
    "Your stomach produces a new layer of mucus every two weeks - otherwise it will digest itself. ",
    "The Declaration of Independence was written on hemp paper. ",
    "A raisin dropped in a glass of fresh champagne will bounce up and down continuously from the bottom of the glass to the top. ",
    "315 entries in Webster's 1996 Dictionary were misspelled. ",
    "Ketchup was sold in the 1830s as medicine. ",
    "Upper and lower case letters are named 'upper' and 'lower' because in the time when all original print had to be set in individual letters, the 'upper case' letters were stored in the case on top of the case that stored the smaller, 'lower case' letters. ",
    "Because metal was scarce, the Oscars given out during World War II were made of wood. ",
    "There are no clocks in Las Vegas gambling casinos. ",
    "The name Wendy was made up for the book Peter Pan, there was never a recorded Wendy before! ",
    "A tiny amount of liquor on a scorpion will make it instantly go mad and sting itself to death. ",
    "The mask used by Michael Myers in the original \"Halloween\" was a Captain Kirk mask painted white. ",
    "If you have three quarters, four dimes, and four pennies, you have $1.19. You also have the largest amount of money in coins without being able to make change for a dollar. ",
    "Guinness Book of Records holds the record for being the book most often stolen from Public Libraries. ",
    "The glue on Israeli postage stamps is certified kosher. ",
    "Chewing gum while peeling onions will keep you from crying! ",
    "Celery has negative calories! It takes more calories to eat a piece of celery than the celery has in it to begin with. It's the same with apples! ",
    "The word \"queue\" is the only word in the English language that is still pronounced the same way when the last four letters are removed. ",
    "Of all the words in the English language, the word ’set’ has the most definitions! ",
    "What is called a \"French kiss\" in the English speaking world is known as an \"English kiss\" in France.",
    "\"Almost\" is the longest word in the English language with all the letters in alphabetical order. ",
    "\"Rhythm\" is the longest English word without a vowel. ",
    "In 1386, a pig in France was executed by public hanging for the murder of a child ",
    "Human thigh bones are stronger than concrete. ",
    "You can’t kill yourself by holding your breath ",
    "It’s against the law to have a pet dog in Iceland.",
    "Your heart beats over 100,000 times a day.",
    "The elephant is the only mammal that can’t jump! ",
    "One quarter of the bones in your body, are in your feet! ",
    "Fingernails grow nearly 4 times faster than toenails! ",
    "Most dust particles in your house are made from dead skin! ",
    "Adolf Hitler was a vegetarian, and had only ONE testicle.",
    "Months that begin on a Sunday will always have a \"Friday the 13th.\"",
    "Coca-Cola would be green if colouring weren’t added to it. ",
    "More people are killed each year from bees than from snakes",
    "The average lead pencil will draw a line 35 miles long or write approximately 50,000 English words. ",
    "More people are allergic to cow’s milk than any other food. ",
    "The placement of a donkey’s eyes in its’ heads enables it to see all four feet at all times! ",
    "It’s against the law to burp, or sneeze in a church in Nebraska, USA. ",
    "Some worms will eat themselves if they can’t find any food! ",
    "The longest recorded flight of a chicken is 13 seconds ",
    "Owls are the only birds who can see the colour blue. ",
    "A giraffe can clean its ears with its 21-inch tongue! ",
    "If you yelled for 8 years, 7 months and 6 days you would have produced enough sound energy to heat one cup of coffee. ",
    "If you farted consistently for 6 years and 9 months, enough gas is produced to create the energy of an atomic bomb.",
    "The human heart creates enough pressure when it pumps out to the body to squirt blood 30 feet.",
    "A pig's orgasm lasts 30 minutes.",
    "Banging your head against a wall uses 150 calories a hour",
    "The flea can jump 350 times its body length. It's like a human jumping the length of a football field.",
    "Some lions mate over 50 times a day.",
    "The strongest muscle in the body is the tongue.",
    "A cat's urine glows under a black light.",
    "Polar bears are left-handed.",
    "Humans and dolphins are the only species that have sex for pleasure.",
    "The average person spends 6 months of their lifetime waiting on a red light to turn green.",
    "You burn more calories sleeping than you do watching television.",
    "If you believe that you’re truly one in a million, there are still approximately 7,632 more people out there just like you.",
    "A single cloud can weight more than 1 million pounds",
    "You cannot snore and dream at the same time.",
    "Earth has traveled more than 5,000 miles in the past 5 minutes.",
    "There are more collect calls on Father’s Day than on any other day of the year.",
    "95% of people text things they could never say in person.",
    "About 150 people per year are killed by coconuts.",
    "Avocados are poisonous to birds.",
    "The word “gorilla” is derived from a Greek word meaning, “A tribe of hairy women.”",
    "Prisoners in Canadian war camps during WWII were treated so well, that a lot of them didn’t’ want to leave when the war was over.",
    "In 2006 someone tried to sell New Zealand on eBay. The price got up to $3,000 before eBay shut it down.",
    "A man from Britain changed his name to Tim Pppppppppprice to make it harder for telemarketers to pronounce.",
    "Cherophobia is the fear of fun.",
    "The chance of you dying on the way to get lottery tickets is actually greater than your chance of winning.",
    "The toothpaste “Colgate” in Spanish translates to “go hang yourself”",
    "A church in the Czech Republic has a chandelier made entirely of human bones.",
    "Our eyes are always the same size from birth, but our nose and ears never stop growing.",
    "ATM’s were originally thought to be failures, because the only users were prostitutes and gamblers who didn’t want to deal with tellers face to face.",
    "Blue-eyed people tend to have the highest tolerance of alcohol.",
    "Every year more than 2500 left-handed people are killed from using right-handed products.",
    "The founders of Google were willing to sell Google for $1 million to Excite in 1999, but Excite turned them down. Google is now worth $527 Billion.",
    "Women have twice as many pain receptors on their body than men. But a much higher pain tolerance."
];

const Discord = require('discord.js');

module.exports.run = async (client, msg, cmds) => {

    var num = Math.floor(Math.random()*124) + 1;

    let factEmbed = new Discord.RichEmbed()
    .setColor("#AA00FF")
    .setTitle(":thinking: Fun Fact! :thinking:")
    .setDescription(funFacts[num])
    .addBlankField()
    .setFooter("Facts from https://bit.ly/2EkDy0F and https://bit.ly/NKwaNY");

    msg.channel.send(factEmbed);

}

module.exports.help = {
    name: "funfact"
}